---
# tasks file for nginx
- name: clone NodeAPI repo
  git: 
    repo: https://github.com/ealeksandrov/NodeAPI.git 
    dest: /tmp/NodeAPI
    force: yes


- name: modify the docker-compose.yml
  copy: 
   src: /data/nodeapi/files/docker-compose.yml
   dest: /tmp/NodeAPI/

- name: install NodeAPI
  shell: export SEQUENCE={{ item }};  docker-compose -p "{{ project_prefix }}{{ item }}"  up -d 
  args:
      chdir: /tmp/NodeAPI
  with_sequence: start=1 end={{ count_of_instances }}

